@echo off
setlocal
set pwd=%~dp0
set build_dir=%pwd%_build
if not exist %build_dir% (
	mkdir %build_dir%
)
set filename=main
::
:: Running pdflatex files with shell escape
pdflatex -synctex=1 -interaction=nonstopmode -shell-escape -output-directory=%build_dir% %pwd%%filename%.tex
::
:: Running asy on all .asy files generated by pdflatex
cd %build_dir%
for %%f in (%filename%-*.asy) do (
    asy %%f
)
cd ..
::
:: Running pdflatex again to include Asymptote figures
pdflatex -synctex=1 -interaction=nonstopmode -shell-escape -output-directory=%build_dir% %pwd%%filename%.tex

echo Compilation completed.
endlocal
rem pause